### ISSUE TITLE
Issues with PackMol and rdkit tests

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmoltools#175]
The PackMol tests appear to be [segfaulting on travis](https://travis-ci.org/choderalab/openmoltools/jobs/105086143#L2852), and on my Mac, they are failing with `rdkit` errors:
```
[LSKI1497:choderalab/openmoltools/openmoltools.jchodera] choderaj% nosetests -vv --nocapture openmoltools/tests/test_packmol.py
nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
test_packmol.test_packmol_simulation_ternary ... ERROR
test_packmol.test_packmol_simulation_ternary_bydensity ... ERROR

======================================================================
ERROR: test_packmol.test_packmol_simulation_ternary
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/choderaj/github/choderalab/openmoltools/openmoltools.jchodera/openmoltools/tests/test_packmol.py", line 26, in test_packmol_simulation_ternary
    ligand_trajectories, ffxml = utils.smiles_to_mdtraj_ffxml(smiles_list)
  File "/Users/choderaj/github/choderalab/openmoltools/openmoltools.jchodera/openmoltools/utils.py", line 354, in smiles_to_mdtraj_ffxml
    m = Chem.AddHs(m)
ArgumentError: Python argument types in
    rdkit.Chem.rdmolops.AddHs(Mol)
did not match C++ signature:
    AddHs(RDKit::ROMol mol, bool explicitOnly=False, bool addCoords=False)

======================================================================
ERROR: test_packmol.test_packmol_simulation_ternary_bydensity
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/choderaj/github/choderalab/openmoltools/openmoltools.jchodera/openmoltools/tests/test_packmol.py", line 60, in test_packmol_simulation_ternary_bydensity
    ligand_trajectories, ffxml = utils.smiles_to_mdtraj_ffxml(smiles_list)
  File "/Users/choderaj/github/choderalab/openmoltools/openmoltools.jchodera/openmoltools/utils.py", line 354, in smiles_to_mdtraj_ffxml
    m = Chem.AddHs(m)
ArgumentError: Python argument types in
    rdkit.Chem.rdmolops.AddHs(Mol)
did not match C++ signature:
    AddHs(RDKit::ROMol mol, bool explicitOnly=False, bool addCoords=False)

----------------------------------------------------------------------
Ran 2 tests in 0.031s

FAILED (errors=2)
```

**Comment by jchodera** [comment]
I've disabled installation of these packages on travis (and hence the tests), but someone (@davidlmobley?) will want to fix the errors and re-enable the tests.

https://github.com/choderalab/openmoltools/pull/176

We aren't using either capability right now, so we won't get to this for a while.

**Comment by davidlmobley** [comment]
We've never used the rdkit components from openmoltools at all. If you guys
aren't using them either, then I'll probably need to disable them to fix
the tests, since we obviously won't get to fixing them in the near future
either. (We ARE using packmol - but not rdkit).

Is it OK with you if we just disable the rdkit components, @jchodera?

(We also don't use the ffxml stuff, which is the other error I see above in
the tests...)

On Tue, Jan 26, 2016 at 9:27 PM, John Chodera <notifications@github.com>
wrote:

> I've disabled installation of these packages on travis (and hence the
> tests), but someone (@davidlmobley <https://github.com/davidlmobley>?)
> will want to fix the errors and re-enable the tests.
>
> #176 <https://github.com/choderalab/openmoltools/pull/176>
>
> We aren't using either capability right now, so we won't get to this for a
> while.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/choderalab/openmoltools/issues/175#issuecomment-175406129>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by jchodera** [comment]
rdkit and packmol tests are disabled for now.

I imagine these components were used in the ThermoML benchmark paper from @kyleabeauchamp and @juliebehr. If we're not actively using them now, I can deprecate them and replace them with an updated infrastructure for OpenMM parameterization.  

Out of curiosity, when you were developing the `packmol` tools for mixtures, did the tests pass locally before the code got checked in?  

We should probably try to solidify an API for small molecule manipulation at some point.  Right now, this just seems to be a grab bag of random useful utilities, which isn't bad, but if we can come up with a coherent API, that would be even better.

**Comment by davidlmobley** [comment]
I had a moment to take a quick look at the code. The current packmol-related tests are older and all utilize RDKit and the ffxml stuff from your lab. They WERE passing the last time we did any code development related to packmol, so I'm guessing someone's more recent changes on the ffxml side of things has broken them...?

Regardless, unless you are planning on using the something along the lines of what's implemented in these tests, the simplest route is probably for me to re-write the tests in the near future so that they don't require RDKit and bypass the ffxml functionality. Is that OK with you, @jchodera ? 

We do have downstream code that relies on the packmol functionality in openmoltools (and which itself is using travis for testing), so it's important to us that openmoltools continue testing packmol. If you're not going to continue supporting RDKit then I need to write some other tests that will ensure our downstream use doesn't get broken.

See for example https://github.com/MobleyLab/SolvationToolkit/blob/master/solvated_mixtures.py#L156

**Comment by davidlmobley** [comment]
Just to reiterate since our comments crossed: We are very much still using packmol, and at least as of the last time we touched anything in openmoltools, that functionality was still working for us. It looks like the issues here are only relating to RDKit and `utils.smiles_to_mdtraj_ffxml(smiles_list)`, neither of which I've ever used.

**Comment by davidlmobley** [comment]
@jchodera : 

> Out of curiosity, when you were developing the packmol tools for mixtures, did the tests pass locally before the code got checked in?`

Not only that, but this code was passing Travis checks until very recently - i.e. I've always seen that these checks passed whenever we were making commits to openmoltools, so something that was changed recently has broken them. Thus, I'm a bit nervous about disabling the tests, since it means something larger is wrong.

I'm certainly sympathetic to the idea that no one is (?) using RDKit and perhaps `utils.smiles_to_mdtraj_ffxml(smiles_list)` so maybe those should be deprecated and removed from the tests (?) but I use `openmoltools.packmol.approximate_volume_by_density` and `openmoltools.packmol.pack_box` downstream so I need them to continue being tested.

**Comment by jchodera** [comment]
> I had a moment to take a quick look at the code. The current packmol-related tests are older and all utilize RDKit and the ffxml stuff from your lab. They WERE passing the last time we did any code development related to packmol, so I'm guessing someone's more recent changes on the ffxml side of things has broken them...?

That code wasn't touched, but I think I know what happened:
* 12 days ago, I had [re-enabled `rdkit` in travis](https://github.com/choderalab/openmoltools/commit/0b4a62a0521b74dc91c61e385e6c5d9ee18664f1) since someone had *disabled* it previously.
* That `rdkit` meant that some packmol tests that use `rdkit` were suddenly running again, and encountered what appears to be an API change in `rdkit`.

I think the rest of the packmol tests will work if I re-enable `packmol` testing but *disable* `rdkit`.

**Comment by jchodera** [comment]
packmol testing re-enabled by https://github.com/choderalab/openmoltools/pull/178

**Comment by davidlmobley** [comment]
I think it's worse than that, because it looks like the packmol tests, as
Kyle wrote them, all require RDKit. So re-enabling packmol testing without
RDKit won't resolve the issue.

It seems like the RDKit API change is the major problem.

I think the simplest thing is for one of us to make simpler packmol tests
that don't rely on RDKit, i.e. just see
https://github.com/MobleyLab/SolvationToolkit/blob/master/solvated_mixtures.py#L156

On Tue, Jan 26, 2016 at 9:58 PM, John Chodera <notifications@github.com>
wrote:

> I had a moment to take a quick look at the code. The current
> packmol-related tests are older and all utilize RDKit and the ffxml stuff
> from your lab. They WERE passing the last time we did any code development
> related to packmol, so I'm guessing someone's more recent changes on the
> ffxml side of things has broken them...?
>
> That code wasn't touched, but I think I know what happened:
>
>    - 12 days ago, I had re-enabled rdkit in travis
>    <https://github.com/choderalab/openmoltools/commit/0b4a62a0521b74dc91c61e385e6c5d9ee18664f1>
>    since someone had *disabled* it previously.
>    - That rdkit meant that some packmol tests that use rdkit were
>    suddenly running again, and encountered what appears to be an API change in
>    rdkit.
>
> I think the rest of the packmol tests will work if I re-enable packmol
> testing but *disable* rdkit.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/choderalab/openmoltools/issues/175#issuecomment-175419141>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by jchodera** [comment]
> Not only that, but this code was passing Travis checks until very recently 

Note that py27 and py34 were passing travis checks, and only py35 was not because the OpenEye toolkit does not yet support py35: https://github.com/choderalab/openmoltools/issues/172

The change in python version support was made in https://github.com/choderalab/openmoltools/pull/165 to match the requirements for `omnia`, which now requires py27, py34, and py35 support.

Also, OpenEye toolkit testing had been silently disabled because the license had expired.  I fixed that in https://github.com/choderalab/openmoltools/commit/8584153c34f4fe8ee354b89285c257a68a35850f 12 days ago.

**Comment by jchodera** [comment]
Did you guys add tests that don't require rdkit?

**Comment by jchodera** [comment]
Looks like things are back to normal:
https://travis-ci.org/choderalab/openmoltools

[`openmoltools-dev` should be pushed for py27 and py34](https://anaconda.org/omnia/openmoltools-dev/files).

**Comment by jchodera** [comment]
Oh, though I'm oddly seeing things work for the current stable oechem release but *fail* for the beta preview oechem release.  That's actually useful to know!
