### ISSUE TITLE
Move amber functions from utils.py to amber.py

### ISSUE THREAD

**Issue by kyleabeauchamp** [choderalab/openmoltools#94]
Also, leave symlinks in the old location with a warning flag up use.

**Comment by davidlmobley** [comment]
Thanks for flagging this again. I agree; it's not high priority but currently it's confusing.

Maybe it would help if we define a quick scope of the modules. I've been thinking of them in terms of workflows - i.e. the `gromacs` module (to be added soon) would be things which are primarily for simulations which are going to be conducted in GROMACS, `amber` for AMBER, etc. But perhaps this is not a good division, since with the upcoming ability to easily convert things between packages (which we already have for AMBER to GROMACS) it will be less relevant which package they are for setting up for.

Perhaps a better division would be that each module should relate to tools connected exclusively with a particular package, and `utils` would contain cross-package tools? So for example, `amber` would include things which only use `amber` tools, `gromacs` things which only use `gromacs` tools, and `utils` would be cross-package tools?

Thanks.
