### ISSUE TITLE
Find better name and add text to README.md

### ISSUE THREAD

**Issue by kyleabeauchamp** [choderalab/openmoltools#95]

**Comment by davidlmobley** [comment]
I forgot to comment on the name issue by e-mail. Maybe the name discussion should start by trying to define the scope (which was one of the issues with mmtools). Are we focused primarily here on setup of simulations of small organic/inorganic molecules in solution? Or does our scope include proteins/nucleic acids (I assume not)? And are we really restricting this to GAFF only? (i.e. if the FF project comes along far enough would we include potentially our own FF in this? My guess would be yes, which would argue against having GAFF in the name. Likewise if the CHARMM or other FFs became easy enough to assign that we could easily include them within this framework, probably we'd be OK with it?)

Assuming it's primarily simulations of small molecules in liquids (of various compositions), perhaps we ought to think about names which invoke that. Maybe, "solution toolkit", "small molecule toolkit", "molecular toolkit/tools", etc. We could probably also resurrect the name "MolTools" if we think it's appropriate - I'm fairly certain we could easily get everyone involved in that to sign off on this as a replacement.

I think we probably ought to avoid names which invoke a particular force field or class of force fields, or a particular file format or simulation package (i.e. the "XML" in the current name was initially a turn-off to me since I don't want XML files at present).

**Comment by kyleabeauchamp** [comment]
I think something like MolTools is good.

**Comment by davidlmobley** [comment]
OK, unless John objects I think we should go with that. I'll just kick off
a quick e-mail thread to the people formerly involved with mmtools to make
sure nobody objects AND see if anyone wants to get involved.

On Wed, Apr 29, 2015 at 8:09 AM, Kyle Beauchamp <notifications@github.com>
wrote:

> I think something like MolTools is good.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/choderalab/gaff2xml/issues/95#issuecomment-97459390>.
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by davidlmobley** [comment]
Seems like everyone is OK with the name change and you started to implement.

**Comment by kyleabeauchamp** [comment]
Fixed in #96
